image: node:13

variables:
  PUBLIC_URL: /react-demo

stages:
  # - test
  - build
  - deploy

# test:
#   stage: test
#   cache:
#     paths:
#       - node_modules/
#   script:
#     - apt-get update
#     - npm install
#     - npm run test

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  script:
    - echo "1"
    - ls
    - mv public repo_public
    - ls
    - mv build public
    - ls public/
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - master